### PR TITLE
Yun/tasks

### PR DESCRIPTION
**Pull request by lonhep-tamfeb**
Contains: task app

### CODE REVIEW

**Comment by hanfel-dovned** [comment]
Closes #24

**Comment by tiller-tolbus** [comment]
AFAIK this cannot be merged until it's compatible with the Sky rewrite (still ongoing)

**Comment by tiller-tolbus** [comment]
We could maybe merge this into the `c1-demos` branch?

**Comment by hanfel-dovned** [comment]
Closing this in favor of #46

**Pull request closed without merging**
