### PR TITLE
Tree view

### LINKED ISSUE #73: tree: full crud
Within Tree, or the "raw view" of Sky, a user should be able to perform any CRUD (create, read, update, delete) operation through a generic interface. 

- [x] Create: User can make a new node of any available type with a state vase input as a text-input noun and a set of dependencies as an expandable text input of `@tas` - `pith`. 
(note: without service discovery, "available types" are just a listing of the files in `our/cod/out/imp`
- [x] Read: Pretty-prints the state of a node as user-readable data
- [x] Update: All studs in the `+poke` arm of the node have a corresponding textbox and "Poke" button. Textbox attempts to render input text as a noun. The stud corresponding to the poke is implicit and does not need to be input by the user. 
- [ ] Delete: %tomb the current node and all children (two clicks: user must confirm deletion)

### PR DESCRIPTION
**Pull request by lonhep-tamfeb**
closes #73

### CODE REVIEW

**Review by will-hanlen — APPROVED** [review]
looks good. let's merge this tomorrow during the workshop and see how it works with the new iframe-based sky

**Comment by hanfel-dovned** [comment]
@liam-fitzgerald How does [this line change](https://github.com/urbit/shrub/pull/81/files#diff-87d570b94b6d660ec4074392cc46bc9a1f5d8096dcdd612614c229b92769401fR276) look in `app/neo.hoon`?

**Comment by liam-fitzgerald** [comment]
Good catch, yeah that's right.

**Comment by will-hanlen** [comment]
this PR has been merged into #101 
@YunPearce

**Pull request closed without merging**
